class Constants:

    SHOOTER_TALON_MAX_SPEED = 1000
    TIMEOUT_MS = 20
  
    SHOOTER_VELOCITY_F = 0
    SHOOTER_VELOCITY_P = 0
    SHOOTER_VELOCITY_I = 0
    SHOOTER_VELOCITY_D = 0

    DRIVETRAIN_F = 0
    DRIVETRAIN_P = 0
    DRIVETRAIN_I = 0
    DRIVETRAIN_D = 0
